mybatis:
  type-aliases-package: com.mashibing.arika.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
      mashibing:
        arika:
          mapper: debug
spring:
#  resources:
#    static-locations: /META-INF/resources/, classpath:/resources/
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: zz
    password: 123456

server:
  port: 8080



